function checkInputInt(a){return/^[1-9][0-9]*$/.test(a)}var Format=[["H","\u9999\u6e2f\u76d8","Y"],["M","\u9a6c\u6765\u76d8","Y"],["I","\u5370\u5c3c\u76d8","Y"],["E","\u6b27\u6d32\u76d8","Y"]];function addComma(a){var b="",c=0>a?"-":"";a=""+Math.abs(a);if(0<=a.indexOf(".")){var e=a.split(".");var d=e[0];b=e[1];e=e[0]}else e=d=a;for(ii=d.length;3<ii;ii-=3){var f=ii-3;d=e.substring(0,f);e=e.substring(f);e=d+","+e}0<=a.indexOf(".")&&(e+="."+b);return c+e}
function Mathfloor(a){return Math.floor(100*a+.01)/100}function printf(a,b){a=""+a;var c=a.split(".");if(1<c.length)for(ii=0;ii<b-c[1].length;ii++)a+="0";else for(a+=".",ii=0;ii<b;ii++)a+="0";return a}
function setFontAction(){$(".top").append('<div id="skin" class="zoomChange">\u5b57\u4f53\u663e\u793a\uff1a<a id="skin_0" data-val="1" class="zoom zoomSmaller" href="javascript:;" title="\u70b9\u51fb\u5207\u6362\u539f\u59cb\u5b57\u4f53">\u5c0f</a><a id="skin_1" data-val="1.2" class="zoom zoomMed " href="javascript:;" title="\u70b9\u51fb\u5207\u6362\u4e2d\u53f7\u5b57\u4f53">\u4e2d</a><a id="skin_2" data-val="1.35" class="zoom zoomBigger" href="javascript:;" title="\u70b9\u51fb\u5207\u6362\u5927\u53f7\u5b57\u4f53">\u5927</a></div>');$(".top").on("click",
    ".zoom",function(){var a=$(this).data("val");sessionStorage.setItem("font_size",a);parent.body_browse.location.reload(!0)});var a=sessionStorage.getItem("font_size");""==a&&(a="1");$(".top").find(".zoom").each(function(){$(this).data("val").toString()==a&&$(this).addClass("selected")});$(".body_browse_set").css({zoom:a,"-moz-transform":"scale("+a+")","-moz-transform-origin":" top left"});$("#page_no").append('<div class="search_box">\n<input type="text" id="seachtext" placeholder="\u8f93\u5165\u5173\u952e\u5b57\u67e5\u8be2" class="select_btn">\n<input type="button" id="btnSearch" value="\u641c\u7d22" class="seach_submit" onclick="seaGameList()">\n</div>')}
function seaGameList(a){(a=$.trim($("#seachtext").val()))?reload_var("",a):reload_var()}function setRefreshPos(){var a=body_browse.document.getElementById("refresh_right");a&&(a.style.left=1*body_browse.document.getElementById("myTable").clientWidth+20)}
function chg_league(){var a=document.getElementById("legView");document.getElementById("myTable");try{legFrame.location.href="./body_var_lid.php?uid="+parent.uid+"&rtype="+parent.rtype+"&langx="+parent.langx+"&mtype="+parent.ltype+"&FStype="+parent.FStype}catch(b){legFrame.src="./body_var_lid.php?uid="+parent.uid+"&rtype="+parent.rtype+"&langx="+parent.langx+"&mtype="+parent.ltype+"&FStype="+parent.FStype}a.style.display=""}
function setBetFastAction(){"undefined"!=typeof $&&$(".betAmount").html(' <ul><li value="100">100</li><li value="200">200</li><li value="500">500</li><li value="1000">1,000</li><li value="5000">5,000</li><li value="10000">10,000</li></ul>')}function fastBetAction(){var a=0;"undefined"!=typeof $&&($(".betAmount").on("click","li",function(){a+=$(this).val();$("#gold").val(a);$("#gold").keyup()}),$("#betClear").click(function(){a=0;$("input[name='gold']").val("").focus();$("#gold").keyup()}))}
function CountWinGold(){var a=document.all.ioradio_r_h.value,b=document.all.gold.value;""==b?(document.all.gold.focus(),document.all.pc.innerHTML="0",top.keepGold=""):(top.keepGold=document.getElementById("gold").value,a=Math.round(b*a*100),a=addComma(a/100),a=printf(a,2),document.all.pc.innerHTML=a,count_win=!0)}
function CountWinGold_dy_ds_dyh(){var a=document.all.ioradio_r_h.value,b=document.all.gold.value;""==b?(document.all.gold.focus(),document.all.pc.innerHTML="0",top.keepGold=""):(top.keepGold=document.getElementById("gold").value,a=Math.round(100*(b*a-b)),a/=100,a=addComma(a),a=printf(a,2),document.all.pc.innerHTML=a,count_win=!0)}
function SubChk(){var a=!1;""==document.all.gold.value?(document.all.gold.focus(),alert(top.message001),a=!0):checkInputInt(document.all.gold.value)?1==isNaN(document.all.gold.value)?(document.all.gold.focus(),alert(top.message002),a=!0):eval(1*document.all.gold.value)<1*document.all.gmin_single.value.replace(",","")?(document.all.gold.focus(),alert(top.message003+" "+top.mcurrency+" "+document.all.gmin_single.value),a=!0):eval(1*document.all.gold.value)>eval(1*document.all.gmax_single.value)?(document.all.gold.focus(),
    alert(top.message004+" "+top.mcurrency+" "+document.all.gmax_single.value),a=!0):"1"!=document.all.pay_type.value?(eval(1*document.all.gold.value)>eval(document.all.singleorder.value)&&(document.all.gold.focus(),alert(top.message006+" "+top.mcurrency+" "+document.all.singleorder.value),a=!0),eval(document.all.restsinglecredit.value)+eval(1*document.all.gold.value)>eval(document.all.singlecredit.value)&&(document.all.gold.focus(),0==eval(document.all.restsinglecredit.value)?alert(top.message007):alert(top.message008+
    document.all.restsinglecredit.value+top.message009),a=!0)):eval(1*document.all.gold.value)>eval(document.all.restcredit.value)&&(document.all.gold.focus(),alert(top.message010),a=!0):(document.all.gold.focus(),alert(top.message002),a=!0);if(a){try{parent.live_order_height(document.body.scrollHeight)}catch(b){}return!1}Open_div();return!1}
function Open_div(){confirm(top.message011+document.all.pc.innerHTML+top.message016)?(document.all.gold.blur(),document.all.btnCancel.disabled=!0,document.all.Submit.disabled=!0,document.all.gold.readOnly=!0,Sure_wager()):Close_div()}function Close_div(){document.all.gWager.style.display="none";document.all.btnCancel.disabled=!1;document.all.Submit.disabled=!1;document.all.gold.readOnly=!1;try{parent.live_order_height(document.body.scrollHeight)}catch(a){}return!1}
function Sure_wager(){document.all.gWager.style.display="none";document.forms[0].submit();parent.onloadSet(document.body.scrollWidth,document.body.scrollHeight,"bet_order_frame")}function js_change_rate(a,b){var c=0;switch(a){case "A":c=.03;break;case "B":c=.01;break;case "C":c=0;break;case "D":c=-.01}""!=b&&"0"!=b?(b=b.toString().replace("<font color='#cc0000'>","").replace("</font>",""),a=(parseFloat(b)-c).toFixed(2),0>=a&&-.03<=a&&(a="")):a="";return a}
function get_other_ioratio(a,b,c,e){var d=[];""!=b||""!=c?d=chg_ior(a,b,c,e):(d[0]=b,d[1]=c);return d}
function chg_ior(a,b,c,e){b=Math.floor(1E3*b+.001)/1E3;c=Math.floor(1E3*c+.001)/1E3;var d=[];11>b&&(b*=1E3);11>c&&(c*=1E3);b=parseFloat(b);c=parseFloat(c);switch(a){case "H":d=get_HK_ior(b,c);break;case "M":d=get_MA_ior(b,c);break;case "I":d=get_IND_ior(b,c);break;case "E":d=get_EU_ior(b,c);break;default:d[0]=b,d[1]=c}d[0]/=1E3;d[1]/=1E3;d[0]=printf(Decimal_point(d[0],e),iorpoints);d[1]=printf(Decimal_point(d[1],e),iorpoints);return d}
function get_HK_ior(a,b){var c=[];if(1E3>=a&&1E3>=b)return c[0]=a,c[1]=b,c;var e=2E3-(a+b);a>b?(a=b,b="C"):b="H";var d=1E3<2E3-e-a?-1*(a+e):2E3-e-a;e=0>d?Math.floor(1E3*Math.abs(1E3/d)):2E3-e-d;"H"==b?(c[0]=a,c[1]=e):(c[0]=e,c[1]=a);return c}function get_MA_ior(a,b){var c=[];if(1E3>=a&&1E3>=b)return c[0]=a,c[1]=b,c;if(a>b){var e=b;var d="C"}else e=a,d="H";a=-1*(e+(2E3-(a+b)));"H"==d?(c[0]=e,c[1]=a):(c[0]=a,c[1]=e);return c}
function get_IND_ior(a,b){var c=get_HK_ior(a,b);a=c[0];b=c[1];a/=1E3;b/=1E3;1>a&&(a=-1/a);1>b&&(b=-1/b);c[0]=1E3*a;c[1]=1E3*b;return c}function get_EU_ior(a,b){var c=get_HK_ior(a,b);a=c[0];b=c[1];c[0]=a+1E3;c[1]=b+1E3;return c}function Decimal_point(a,b){var c=0>a?"Y":"N";a=Math.floor(Math.abs(a)*b+1/b)/b;return a*("Y"==c?-1:1)}
function formatNumber(a,b,c){for(var e=b,d=1;0<b;d*=10,b--);b=0==b?0:1/d;return 0<=1*a?c?addZero(Math.round(a*d+b)/d,e):Math.round(a*d+b)/d:c?addZero(Math.round(a*d-b)/d,e):Math.round(a*d+b)/d}function addZero(a,b){a+="";var c="",e=a.indexOf(".");-1==e&&(a+=".",e=a.length-1);b=1*b-(a.length-e-1);for(e=0;e<b;e++)c+="0";return a+c}function in_array(a,b){for(var c=0;c<=b.length;c++)if(a==b[c])return!0;return!1};