function bodyLoad(){close_bet()}function showSportMenu(){try{bet_order_frame.clearAllTimer()}catch(a){}try{close_bet()}catch(a){}$("#bet_div,#rec5_div").hide();$("#div_menu").show();document.getElementById("order_button").className="ord_btn";document.getElementById("record_button").className="record_btn";document.getElementById("menu_button").className="menu_on"}
function showOrder(){try{bet_order_frame.resetTimer()}catch(e){}document.getElementById("rec_frame").height=0;rec_frame.document.close();document.getElementById("order_button").className="ord_on";document.getElementById("record_button").className="record_btn";document.getElementById("menu_button").className="menu";var a=document.getElementById("bet_div"),c=document.getElementById("rec5_div"),d=document.getElementById("div_menu");a.style.display="block";c.style.display="none";d.style.display="none";
    document.getElementById("pls_bet").style.display="none";addOrderContent()}
function showRec(){try{bet_order_frame.clearAllTimer()}catch(d){}try{close_bet()}catch(d){}document.getElementById("order_button").className="ord_btn";document.getElementById("record_button").className="record_on";var a=document.getElementById("bet_div"),c=document.getElementById("rec5_div");document.getElementById("div_menu").style.display="none";a.style.display="none";c.style.display="block";rec5_div.focus();rec_frame.location.replace("./today/show10rec.php?uid="+top.uid+"&langx="+top.langx);document.getElementById("pls_bet").style.display=
    "none"}function addOrderContent(){bet_order_frame.document.close();bet_order_frame.document.writeln("<html><body  class='bet_info'style='padding: 0;margin: 0'>");bet_order_frame.document.writeln(document.getElementById("pls_bet").innerHTML);bet_order_frame.document.writeln("</body></html>");document.getElementById("bet_order_frame").height=bet_order_frame.document.body.scrollHeight}
function onloadSet(a,c,d){document.getElementById(d).width=200;document.getElementById(d).height=c;document.getElementById("pls_bet").style.display="none"}
function betOrder(a,c,d,e){"P3"!=c&&"PR"!=c&&(top.keepGold="",top.keepGold_PR="");top.ioradio="";a=parseUrl(a,c,d,e);document.getElementById("order_button").className="ord_on";document.getElementById("record_button").className="record_btn";document.getElementById("menu_button").className="menu";document.getElementById("pls_bet").style.display="none";document.getElementById("rec_frame").height=0;rec_frame.document.close();document.getElementById("rec5_div").style.display="none";document.getElementById("div_menu").style.display=
    "none";document.getElementById("bet_div").style.display="block";bet_order_frame.location.replace(a)}
function parseUrl(a,c,d,e){var b=[],g=["ROUH","ROUC","HRUH","HRUC"],h=["OUH","OUC","HOUH","HOUC"];b.R=Array("../"+a+"_order/"+a+"_order_r.php");b.HR=Array("../"+a+"_order/"+a+"_order_hr.php");b.OU=Array("../"+a+"_order/"+a+"_order_ou.php");b.HOU=Array("../"+a+"_order/"+a+"_order_hou.php");b.M=Array("../"+a+"_order/"+a+"_order_m.php");b.HM=Array("../"+a+"_order/"+a+"_order_hm.php");b.EO=Array("../"+a+"_order/"+a+"_order_t.php");b.REO=Array("../"+a+"_order/"+a+"_order_rt.php");b.HEO=Array("../"+a+"_order/"+
    a+"_order_t.php");b.HREO=Array("../"+a+"_order/"+a+"_order_rt.php");b.PD=Array("../"+a+"_order/"+a+"_order_pd.php");b.HPD=Array("../"+a+"_order/"+a+"_order_hpd.php");b.HRPD=Array("../"+a+"_order/"+a+"_order_hrpd.php");b.RPD=Array("../"+a+"_order/"+a+"_order_rpd.php");b.F=Array("../"+a+"_order/"+a+"_order_f.php");b.RF=Array("../"+a+"_order/"+a+"_order_rf.php");b.T=Array("../"+a+"_order/"+a+"_order_t.php");b.HT=Array("../"+a+"_order/"+a+"_order_t.php");b.RT=Array("../"+a+"_order/"+a+"_order_rt.php");
    b.HRT=Array("../"+a+"_order/"+a+"_order_rt.php");b.SP=Array("../"+a+"_order/"+a+"_order_sp.php");b.P=Array("../"+a+"_order/"+a+"_order_p.php");b.P3=Array("../"+a+"_order/"+a+"_order_p3.php");b.PR=Array("../"+a+"_order/"+a+"_order_pr.php");b.RE=Array("../"+a+"_order/"+a+"_order_re.php");b.HRE=Array("../"+a+"_order/"+a+"_order_hre.php");b.ROU=Array("../"+a+"_order/"+a+"_order_rou.php");b.HROU=Array("../"+a+"_order/"+a+"_order_hrou.php");b.RM=Array("../"+a+"_order/"+a+"_order_rm.php");b.HRM=Array("../"+
        a+"_order/"+a+"_order_hrm.php");b.NFS=Array("../"+a+"_order/"+a+"_order_nfs.php");b.AR=Array("../"+a+"_order/"+a+"_order_r15.php");b.AOU=Array("../"+a+"_order/"+a+"_order_ou15.php");b.AM=Array("../"+a+"_order/"+a+"_order_m15.php");b.BR=Array("../"+a+"_order/"+a+"_order_r15.php");b.BOU=Array("../"+a+"_order/"+a+"_order_ou15.php");b.BM=Array("../"+a+"_order/"+a+"_order_m15.php");b.CR=Array("../"+a+"_order/"+a+"_order_r15.php");b.COU=Array("../"+a+"_order/"+a+"_order_ou15.php");b.CM=Array("../"+a+"_order/"+
        a+"_order_m15.php");b.DR=Array("../"+a+"_order/"+a+"_order_r15.php");b.DOU=Array("../"+a+"_order/"+a+"_order_ou15.php");b.DM=Array("../"+a+"_order/"+a+"_order_m15.php");b.ER=Array("../"+a+"_order/"+a+"_order_r15.php");b.EOU=Array("../"+a+"_order/"+a+"_order_ou15.php");b.EM=Array("../"+a+"_order/"+a+"_order_m15.php");b.FR=Array("../"+a+"_order/"+a+"_order_r15.php");b.FOU=Array("../"+a+"_order/"+a+"_order_ou15.php");b.FM=Array("../"+a+"_order/"+a+"_order_m15.php");b.TS=Array("../"+a+"_order/"+a+"_order_single.php");
    b.HTS=Array("../"+a+"_order/"+a+"_order_single.php");b.WM=Array("../"+a+"_order/"+a+"_order_single.php");b.DC=Array("../"+a+"_order/"+a+"_order_single.php");b.CS=Array("../"+a+"_order/"+a+"_order_single.php");b.WN=Array("../"+a+"_order/"+a+"_order_single.php");b.MOUA=Array("../"+a+"_order/"+a+"_order_single.php");b.MOUB=Array("../"+a+"_order/"+a+"_order_single.php");b.MOUC=Array("../"+a+"_order/"+a+"_order_single.php");b.MOUD=Array("../"+a+"_order/"+a+"_order_single.php");b.MTS=Array("../"+a+"_order/"+
        a+"_order_single.php");b.OUTA=Array("../"+a+"_order/"+a+"_order_single.php");b.OUTB=Array("../"+a+"_order/"+a+"_order_single.php");b.OUTC=Array("../"+a+"_order/"+a+"_order_single.php");b.OUTD=Array("../"+a+"_order/"+a+"_order_single.php");b.MPG=Array("../"+a+"_order/"+a+"_order_single.php");b.F2G=Array("../"+a+"_order/"+a+"_order_single.php");b.F3G=Array("../"+a+"_order/"+a+"_order_single.php");b.HG=Array("../"+a+"_order/"+a+"_order_single.php");b.MG=Array("../"+a+"_order/"+a+"_order_single.php");
    b.SB=Array("../"+a+"_order/"+a+"_order_single.php");b.FG=Array("../"+a+"_order/"+a+"_order_single.php");b.T3G=Array("../"+a+"_order/"+a+"_order_single.php");b.T1G=Array("../"+a+"_order/"+a+"_order_single.php");b.DUA=Array("../"+a+"_order/"+a+"_order_single.php");b.DUB=Array("../"+a+"_order/"+a+"_order_single.php");b.DUC=Array("../"+a+"_order/"+a+"_order_single.php");b.DUD=Array("../"+a+"_order/"+a+"_order_single.php");b.DS=Array("../"+a+"_order/"+a+"_order_single.php");b.DG=Array("../"+a+"_order/"+
        a+"_order_single.php");b.OUEA=Array("../"+a+"_order/"+a+"_order_single.php");b.OUEB=Array("../"+a+"_order/"+a+"_order_single.php");b.OUEC=Array("../"+a+"_order/"+a+"_order_single.php");b.OUED=Array("../"+a+"_order/"+a+"_order_single.php");b.OUPA=Array("../"+a+"_order/"+a+"_order_single.php");b.OUPB=Array("../"+a+"_order/"+a+"_order_single.php");b.OUPC=Array("../"+a+"_order/"+a+"_order_single.php");b.OUPD=Array("../"+a+"_order/"+a+"_order_single.php");b.W3=Array("../"+a+"_order/"+a+"_order_single.php");
    b.BH=Array("../"+a+"_order/"+a+"_order_single.php");b.WE=Array("../"+a+"_order/"+a+"_order_single.php");b.WB=Array("../"+a+"_order/"+a+"_order_single.php");b.TK=Array("../"+a+"_order/"+a+"_order_single.php");b.OUH=Array("../"+a+"_order/"+a+"_order_single.php");b.OUC=Array("../"+a+"_order/"+a+"_order_single.php");b.HOUH=Array("../"+a+"_order/"+a+"_order_single.php");b.HOUC=Array("../"+a+"_order/"+a+"_order_single.php");void 0==b[c]&&e&&(in_array(c,["ROUH","ROUC"])&&(b[c]=Array("../"+a+"_order/"+a+
        "_order_rouhc.php")),in_array(c,"HRUH HRUC RTS RTS2 RHTS RWM RDC RCS RWN RMUA RMUB RMUC RMUD RMTS RUTA RUTB RUTC RUTD RMPG RF2G RF3G RHG RMG RSB RFG RT3G RT1G RDUA RDUB RDUC RDUD RDS RDG RUEA RUEB RUEC RUED RUPA RUPB RUPC RUPD RW3 RBH RWE RWB RTK ARG".split(" "))&&(b[c]=Array("../"+a+"_order/"+a+"_order_rsingle.php")),in_array(c,"ARR BRR CRR DRR ERR FRR".split(" "))&&(b[c]=Array("../"+a+"_order/"+a+"_order_rr15.php")),in_array(c,"AROU BROU CROU DROU EROU FROU".split(" "))&&(b[c]=Array("../"+a+"_order/"+
        a+"_order_rou15.php")),in_array(c,"ARM BRM CRM DRM ERM FRM".split(" "))&&(b[c]=Array("../"+a+"_order/"+a+"_order_rm15.php")));if("BK"==a){for(var f in h)c==h[f]&&(c="OUHC");for(f in g)c==g[f]&&(c="ROUHC");b.ROUHC=Array("../"+a+"_order/"+a+"_order_rouhc.php");b.OUHC=Array("../"+a+"_order/"+a+"_order_ouhc.php")}c="SP"==c&&"FT"==a?b[c]+"?"+d+"&wtype="+c:0>d.indexOf("&wtype=")?b[c]+"?"+d+"&wtype="+c:b[c]+"?"+d;e&&"FT"==a&&(c=c+"&flag=all&id="+e);e&&"BK"==a&&(c=c+"&id="+e);return c}
function in_array(a,c){for(var d=0;d<=c.length;d++)if(a==c[d])return!0;return!1}function close_bet(){document.getElementById("pls_bet").style.display="none";document.getElementById("bet_div").style.display="none";document.getElementById("bet_order_frame").height=0;document.getElementById("menu_button").className="menu_on";document.getElementById("order_button").className="order_button";document.getElementById("div_menu").style.display="block";top.scripts=[]}
function show_record(){parent.show="N"==parent.show||"undefined"==""+parent.show?"":"N";self.location="./select.php?uid="+top.uid+"&langx="+top.langx+"&show="+parent.show}function reload_var(){parent.refresh_var="Y";self.location.reload()}var xmlHttp;
function createXHR(){window.XMLHttpRequest?xmlHttp=new XMLHttpRequest:window.ActiveXObject&&(xmlHttp=new ActiveXObject("Microsoft.XMLHTTP"));if(!xmlHttp)return alert("\u60a8\u4f7f\u7528\u7684\u700f\u89bd\u5668\u4e0d\u652f\u63f4 XMLHTTP \u7269\u4ef6"),!1}function sendRequest(a){createXHR();xmlHttp.open("GET",a,!0);xmlHttp.onreadystatechange=catchResult;xmlHttp.send(null)}
function catchResult(){4==xmlHttp.readyState&&(s=xmlHttp.responseText,200==xmlHttp.status?(document.getElementById("showURL").innerHTML=s,document.getElementById("newdomain").submit()):alert("\u57f7\u884c\u932f\u8aa4,\u4ee3\u78bc:"+xmlHttp.status+"("+xmlHttp.statusText+")"))}
function showHotDiv(a){var c=document.getElementById("hot_div_"+a);document.getElementById("arrow_"+a);if(disHash["HOT_"+a]){var d="none";var e=!1}else d="",e=!0;disHash["HOT_"+a]=e;c.style.display=d;a==maxHash.gtype&&(document.getElementById("hot_show").className=""==d?"ord_sportMenu_high2":"ord_sportMenu_high")}
function addGameCls(){switch(top.head_gtype){case "FT":top.cgTypebtn="re_class";$("#title_FT").addClass("ord_sportFT_on");comshowtype||$("#wager_FT").addClass("show_game_list");break;default:var a=top.head_gtype.toLowerCase();top.cgTypebtn=""+a+"_re_class";$("#title_"+top.head_gtype).addClass("ord_sport"+top.head_gtype+"_on");comshowtype||$("#wager_"+top.head_gtype).addClass("show_game_list")}};