<?

//测试
//$api_merchant['merchantname'] = 'uat_SYfg113';
//$api_merchant['merchantcode'] = "196f947f9c00ee8e20af23cc0d5b5926";
// HG3366生产
$api_merchant['merchantname'] = 'SYfg113-hg3366';
$api_merchant['merchantcode'] = "c37589a9575a6f28ca00c585bc152a91";


$fg_root_url = "https://" . $api_merchant['merchantname'] . ".fgipa.net";  // 生产
//$fg_root_url = "https://api.ppro.98078.net"; //测试


$fg_member_ext_ref = $owner_id = '3366'; // 平台标识（2-50）
$fg_prefix =  $fg_member_ext_ref.'_'; // 平台前缀  $fg_member_ext_ref.'_'


$timezone = "UTC-4"; // UTC-4 美东时间，UTC+8 北京时间
$currency = "CNY"; // USD, CNY, GBP, EUR
$language = "zh-cn"; // 目前全額提供 zh-cn ,en 多數已支援 th


$page = 1;  //注單查詢
$pagesize = 3000;  //注單查詢

//

/**
 * 备注
 * name  游戏名称
 * gametype 水果机 fruit (arcade) 、 棋牌 poker(chess)、捕猎游戏fish 、 老虎机 slot
 * gamecode 游戏代码
 * img  方形游戏图片资源
 * service_id  游戏id
 * game_url    游戏地址
 * small_img   圆形游戏图片资源
 */
$aFgGames =  array(
    /*水果机 fruit (arcade)*/
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=lztb&language=zh-cn",
        "gamecode" => "lztb",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2019091100045726431.png",
        "ishot" =>0,
        "name" => "龙珠探宝",
        "service_id" =>7023,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019091100045994650.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bcbm&language=zh-cn",
        "gamecode" => "bcbm",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2019091100024934111.png",
        "ishot" =>0,
        "name" => "奔驰宝马2",
        "service_id" =>7026,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019091100025278992.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=cp&language=zh-cn",
        "gamecode" => "cp",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2019080102220658228.png",
        "ishot" =>0,
        "name" => "糖果派对",
        "service_id" =>7021,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019080102220921274.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=si&language=zh-cn",
        "gamecode" => "si",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017120622532622532.png",
        "ishot" =>1,
        "name" => "连环夺宝",
        "service_id" =>7011,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905312197059.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fia&language=zh-cn",
        "gamecode" => "fia",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2018030423280211601.png",
        "ishot" =>1,
        "name" => "浮岛历险记",
        "service_id" =>7016,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905215397854.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bzb&language=zh-cn",
        "gamecode" => "bzb",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092105214197054.png",
        "ishot" =>1,
        "name" => "奔驰宝马",
        "service_id" =>7002,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905211769595.png",
    ),
    /*array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gls&language=zh-cn",
        "gamecode" => "gls",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017120501340084757.png",
        "ishot" =>1,
        "name" => "好运射击",
        "service_id" =>7014,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905252827204.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=tkof&language=zh-cn",
        "gamecode" => "tkof",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2018052204174799573.png",
        "ishot" =>1,
        "name" => "王者足球",
        "service_id" =>7019,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905220365879.png",
    ),*/
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fl&language=zh-cn",
        "gamecode" => "fl",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2018030423293781465.png",
        "ishot" =>0,
        "name" => "水果传奇",
        "service_id" =>7017,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109231436256.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=api&language=zh-cn",
        "gamecode" => "api",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2018020822085039660.png",
        "ishot" =>0,
        "name" => "萌宠夺宝",
        "service_id" =>7018,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071203524827523.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gw&language=zh-cn",
        "gamecode" => "gw",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017120501303660679.png",
        "ishot" =>0,
        "name" => "黄金大转轮",
        "service_id" =>7008,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018082923042788931.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=lucky&language=zh-cn",
        "gamecode" => "lucky",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111221474538093.png",
        "ishot" =>0,
        "name" =>"幸运5",
        "service_id" =>7012,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018082321332812763.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mr&language=zh-cn",
        "gamecode" => "mr",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2018030423273649362.png",
        "ishot" =>0,
        "name" => "猴子爬树",
        "service_id" =>7015,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109215864284.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fod&language=zh-cn",
        "gamecode" => "fod",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091211550229852.png",
        "ishot" =>0,
        "name" => "森林舞会",
        "service_id" =>7003,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109214047298.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=frt&language=zh-cn",
        "gamecode" => "frt",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092105340965255.png",
        "ishot" =>0,
        "name" =>"水果机",
        "service_id" =>7000,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109311252759.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bbs&language=zh-cn",
        "gamecode" => "bbs",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091914251669927.png",
        "ishot" =>0,
        "name" => "飞禽走兽",
        "service_id" =>7001,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109212161074.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fw&language=zh-cn",
        "gamecode" => "fw",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111504222166379.png",
        "ishot" =>0,
        "name" => "水果转盘",
        "service_id" =>7009,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018082321330284217.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hr&language=zh-cn",
        "gamecode" => "hr",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112707130657876.png",
        "ishot" =>0,
        "name" =>"赛马",
        "service_id" =>7010,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109262458208.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=chz&language=zh-cn",
        "gamecode" => "chz",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091212180618633.png",
        "ishot" =>0,
        "name" => "十二生肖",
        "service_id" =>7005,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109303877569.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=con&language=zh-cn",
        "gamecode" => "con",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091914235788418.png",
        "ishot" =>0,
        "name" => "十二星座",
        "service_id" =>7004,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109302523181.png",
    ),
    /*array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bif&language=zh-cn",
        "gamecode" => "bif",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091211594883318.png",
        "ishot" =>0,
        "name" => "燃烧吧，足球",
        "service_id" =>7006,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109305973115.png",
    ),
    array(
        "categoryid" =>10,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=pbb&language=zh-cn",
        "gamecode" => "pbb",
        "gt" => "fruit",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092105324096564.png",
        "ishot" =>0,
        "name" => "巅峰篮球",
        "service_id" =>7007,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109252562791.png",
    ),*/

    /*棋牌 poker(chess)*/
    /*array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=kpqznn&language=zh-cn",   //游戏地址
        "gamecode" => "kpqznn",      //游戏代码
        "gt" => "poker",        //
        "img" => "https://h5.chichengwl.com/global/files/images/2019103004413722982.png",  //方形游戏图片资源
        "ishot" =>0,    //是否热门(0 非热门,1 热门
        "name" => "看牌抢庄牛牛",    // 游戏名称
        "service_id" =>6017,   // 游戏 id
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019103004413943943.png",   //圆形游戏图片资源
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=brtb&language=zh-cn",
        "gamecode" => "brtb",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019103004363653444.png",
        "ishot" =>0,
        "name" => "百人骰宝",
        "service_id" =>6016,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019103004363850095.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ggdqq&language=zh-cn",
        "gamecode" => "ggdqq",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019091100105861242.png",
        "ishot" =>0,
        "name" => "关秦龙虎斗",
        "service_id" =>6015,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019093000025782559.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=slhb&language=zh-cn",
        "gamecode" => "slhb",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019080206370347471.png",
        "ishot" =>0,
        "name" => "扫雷红包",
        "service_id" =>6508,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019080206370541646.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=qznn3d&language=zh-cn",
        "gamecode" => "qznn3d",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019080102190289838.png",
        "ishot" =>0,
        "name" => "抢庄牛牛3D",
        "service_id" =>6701,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019080102190595038.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hlmj3D&language=zh-cn",
        "gamecode" => "hlmj3D",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019080102170012504.png",
        "ishot" =>0,
        "name" => "欢乐麻将3D",
        "service_id" =>6702,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019080102170366754.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ldnmw3D&language=zh-cn",
        "gamecode" => "ldnmw3D",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019080102140214360.png",
        "ishot" =>0,
        "name" => "乐斗牛魔王3D",
        "service_id" =>6703,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019080102140536224.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wxhh&language=zh-cn",
        "gamecode" => "wxhh",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019080102112444699.png",
        "ishot" =>0,
        "name" => "五星宏辉",
        "service_id" =>6507,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019080102112633632.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bj&language=zh-cn",
        "gamecode" => "bj",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019042406142939921.png",
        "ishot" =>0,
        "name" =>"21点",
        "service_id" =>6010,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019042406143277730.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xzdd&language=zh-cn",
        "gamecode" => "xzdd",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019031223311526093.png",
        "ishot" =>0,
        "name" => "欢乐麻将",
        "service_id" =>6667,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019031223311751395.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hlhb&language=zh-cn",
        "gamecode" => "hlhb",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012222072762340.png",
        "ishot" =>0,
        "name" => "欢乐红包",
        "service_id" =>6506,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012222073122678.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zjhdr&language=zh-cn",
        "gamecode" => "zjhdr",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091902243121499.png",
        "ishot" =>0,
        "name" => "经典炸金花",
        "service_id" =>6302,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905283613079.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=iPoker&language=zh-cn",
        "gamecode" => "iPoker",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018101623540269859.png",
        "ishot" =>0,
        "name" => "欢乐德州",
        "service_id" =>6666,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018101623540470476.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=tbnn&language=zh-cn",
        "gamecode" => "tbnn",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823551152730.png",
        "ishot" =>0,
        "name" => "通比牛牛",
        "service_id" =>6504,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905284982262.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=sss&language=zh-cn",
        "gamecode" => "sss",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823514457700.png",
        "ishot" =>0,
        "name" =>"十三水",
        "service_id" =>6011,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905281316203.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ShowHand&language=zh-cn",
        "gamecode" => "ShowHand",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018101623564219403.png",
        "ishot" =>0,
        "name" =>"梭哈",
        "service_id" =>6303,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018101623564513621.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ddz&language=zh-cn",
        "gamecode" => "ddz",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012222095368658.png",
        "ishot" =>0,
        "name" =>"斗地主",
        "service_id" =>6301,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012222095656384.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=qzpj&language=zh-cn",
        "gamecode" => "qzpj",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823540553121.png",
        "ishot" =>0,
        "name" => "抢庄牌九",
        "service_id" =>6013,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018092806092013156.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ebg&language=zh-cn",
        "gamecode" => "ebg",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018092806281427843.png",
        "ishot" =>0,
        "name" =>"二八杠",
        "service_id" =>6012,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018092806281727039.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jszjh&language=zh-cn",
        "gamecode" => "jszjh",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823564363909.png",
        "ishot" =>0,
        "name" => "极速炸金花",
        "service_id" =>6014,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905292389885.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=csg&language=zh-cn",
        "gamecode" => "csg",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050402575689913.png",
        "ishot" =>1,
        "name" =>"三公",
        "service_id" =>6502,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905210611944.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=tz&language=zh-cn",
        "gamecode" => "tz",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050322044016305.png",
        "ishot" =>1,
        "name" =>"骰宝",
        "service_id" =>6005,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905250353863.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=cqznn&language=zh-cn",
        "gamecode" => "cqznn",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019031223471637283.png",
        "ishot" =>1,
        "name" => "抢庄牛牛",
        "service_id" =>6501,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019031223471851186.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mj&language=zh-cn",
        "gamecode" => "mj",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050322035296547.png",
        "ishot" =>0,
        "name" => "二人麻将",
        "service_id" =>6007,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018081300080275855.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bjl&language=zh-cn",
        "gamecode" => "bjl",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019031223340869389.png",
        "ishot" =>0,
        "name" =>"百家乐",
        "service_id" =>6006,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019031223341018865.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jgf&language=zh-cn",
        "gamecode" => "jgf",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012222112650706.png",
        "ishot" =>0,
        "name" => "红黑大战",
        "service_id" =>6008,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012222112883198.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=TexasCb&language=zh-cn",
        "gamecode" => "TexasCb",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050322042399518.png",
        "ishot" =>0,
        "name" => "德州牛仔",
        "service_id" =>6009,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109164484319.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=RC&language=zh-cn",
        "gamecode" => "RC",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050322101460552.png",
        "ishot" =>0,
        "name" => "皇家宫殿",
        "service_id" =>6002,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109144271749.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=HB&language=zh-cn",
        "gamecode" => "HB",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2019031223350572810.png",
        "ishot" =>0,
        "name" => "百人牛牛",
        "service_id" =>6003,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019031223350864752.png",
    ),
    array(
        "categoryid" =>6,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=rt&language=zh-cn",
        "gamecode" => "rt",
        "gt" => "poker",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050322104374261.png",
        "ishot" =>0,
        "name" => "皇家德州",
        "service_id" =>6004,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109124047402.png",
    ),*/

    /*捕猎游戏fish*/
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_lsdr&language=zh-cn",
        "gamecode" => "fish_lsdr",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2019103004264432900.png",
        "ishot" =>0,
        "name" => "猎鼠达人3D",
        "service_id" =>5008,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019103004264758484.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_mrycs&language=zh-cn",
        "gamecode" =>  "fish_mrycs",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2019091100085330134.png",
        "ishot" =>0,
        "name" => "美人鱼传说",
        "service_id" =>5009,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019091100085671565.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_3D&language=zh-cn",
        "gamecode" => "fish_3D",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2019031223451151376.png",
        "ishot" =>0,
        "name" => "捕鱼来了3D",
        "service_id" =>5006,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019031223451395784.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_mfwz&language=zh-cn",
        "gamecode" => "fish_mfwz",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2019031104204217132.png",
        "ishot" =>0,
        "name" => "魔法王者",
        "service_id" =>5007,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019031104204853219.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_mm&language=zh-cn",
        "gamecode" => "fish_mm",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2018010902155118156.png",
        "ishot" =>1,
        "name" => "美人捕鱼",
        "service_id" =>5001,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905201333044.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_hl&language=zh-cn",
        "gamecode" => "fish_hl",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092015140262764.png",
        "ishot" =>1,
        "name" => "欢乐捕鱼",
        "service_id" =>5004,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905203593392.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_tt&language=zh-cn",
        "gamecode" => "fish_tt",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092015152393986.png",
        "ishot" =>1,
        "name" => "天天捕鱼",
        "service_id" =>5005,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905204582243.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_bn&language=zh-cn",
        "gamecode" => "fish_bn",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091606491560390.png",
        "ishot" =>1,
        "name" => "捕鸟达人",
        "service_id" =>5003,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905202435866.png",
    ),
    array(
        "categoryid" =>7,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fish_zj&language=zh-cn",
        "gamecode" => "fish_zj",
        "gt" => "fish",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091414141164251.png",
        "ishot" =>0,
        "name" => "雷霆战警",
        "service_id" =>5002,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018082103290764370.png",
    ),

    /*老虎机 slot*/
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=qhb&language=zh-cn",
        "gamecode" => "qhb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019103004332292936.png",
        "ishot" =>0,
        "name" => "抢红包2",
        "service_id" =>3321,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019103004332417692.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xjpm&language=zh-cn",
        "gamecode" => "xjpm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019103004311834167.png",
        "ishot" =>0,
        "name" => "金瓶梅2",
        "service_id" =>3320,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019103004312088601.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=yxsh&language=zh-cn",
        "gamecode" => "yxsh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019103004274266555.png",
        "ishot" =>0,
        "name" => "水浒英雄",
        "service_id" =>3319,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019103004274475407.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fff&language=zh-cn",
        "gamecode" => "fff",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019042406381635354.png",
        "ishot" =>0,
        "name" =>"发发发",
        "service_id" =>2534,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019042406381849200.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mawm&language=zh-cn",
        "gamecode" => "mawm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019042406352299498.png",
        "ishot" =>0,
        "name" => "街机水浒传",
        "service_id" =>3318,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019042406352515916.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=dfdc&language=zh-cn",
        "gamecode" => "dfdc",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012902302929651.png",
        "ishot" =>0,
        "name" => "多福多财",
        "service_id" =>2284,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012902303220064.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ny&language=zh-cn",
        "gamecode" => "ny",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012902283071232.png",
        "ishot" =>0,
        "name" =>"新年",
        "service_id" =>2283,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012902283363673.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=party&language=zh-cn",
        "gamecode" => "party",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012221540955248.png",
        "ishot" =>0,
        "name" => "水果派对",
        "service_id" =>2531,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012221541235209.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mcm&language=zh-cn",
        "gamecode" => "mcm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2019012222030275323.png",
        "ishot" =>0,
        "name" => "百变猴子",
        "service_id" =>3317,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2019012222030512501.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mcrazy7&language=zh-cn",
        "gamecode" => "mcrazy7",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823540080724.png",
        "ishot" =>0,
        "name" =>"疯狂七",
        "service_id" =>3313,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905275140559.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=qqh&language=zh-cn",
        "gamecode" => "qqh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823530273373.png",
        "ishot" =>0,
        "name" =>"鹊桥会",
        "service_id" =>2532,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905273840516.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mtitanic&language=zh-cn",
        "gamecode" => "mtitanic",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823545661693.png",
        "ishot" =>0,
        "name" => "泰坦尼克号",
        "service_id" =>3315,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905280287194.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zzx&language=zh-cn",
        "gamecode" => "zzx",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823501318776.png",
        "ishot" =>0,
        "name" =>"蜘蛛侠",
        "service_id" =>2282,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905263532627.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gghz&language=zh-cn",
        "gamecode" => "gghz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823512347216.png",
        "ishot" =>0,
        "name" => "古怪猴子",
        "service_id" =>2530,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905264669762.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fastf&language=zh-cn",
        "gamecode" => "fastf",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091823482853729.png",
        "ishot" =>0,
        "name" => "速度与激情",
        "service_id" =>2281,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905290261905.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mboombeach&language=zh-cn",
        "gamecode" =>  "mboombeach",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018092604130557464.png",
        "ishot" =>0,
        "name" => "海岛奇兵",
        "service_id" =>3314,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018092604123314312.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jpm&language=zh-cn",
        "gamecode" => "jpm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022591957361.png",
        "ishot" =>1,
        "name" =>"金瓶梅",
        "service_id" =>2520,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2520.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zcjb&language=zh-cn",
        "gamecode" => "zcjb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018033005334238588.png",
        "ishot" =>1,
        "name" => "招财进宝",
        "service_id" =>2275,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905181384408.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mqhb&language=zh-cn",
        "gamecode" => "mqhb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018012705544479250.png",
        "ishot" =>1,
        "name" =>"抢红包",
        "service_id" =>3307,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3307.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mdl&language=zh-cn",
        "gamecode" => "mdl",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112703261952067.png",
        "ishot" =>1,
        "name" => "钻石之恋",
        "service_id" =>3302,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905195629042.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xsjr&language=zh-cn",
        "gamecode" => "xsjr",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018042722082488327.png",
        "ishot" =>1,
        "name" => "湛蓝深海",
        "service_id" =>2276,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905185741075.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xy&language=zh-cn",
        "gamecode" => "xy",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916421913756.png",
        "ishot" =>1,
        "name" =>"西游",
        "service_id" =>2505,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2505.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mslwh&language=zh-cn",
        "gamecode" => "mslwh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018032022170448249.png",
        "ishot" =>1,
        "name" => "森林舞会",
        "service_id" =>3309,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3309.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gtmymn&language=zh-cn",
        "gamecode" => "gtmymn",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018033005352435355.png",
        "ishot" =>1,
        "name" => "哥谭魅影猫女",
        "service_id" =>2274,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905222653525.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ghxc&language=zh-cn",
        "gamecode" => "ghxc",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018012907493581740.png",
        "ishot" =>1,
        "name" => "恭贺新春",
        "service_id" =>2525,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905225682998.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=rywz&language=zh-cn",
        "gamecode" => "rywz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916450228612.png",
        "ishot" =>1,
        "name" => "荣耀王者",
        "service_id" =>2509,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2509.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=aijinw&language=zh-cn",
        "gamecode" => "aijinw",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018031605350442734.png",
        "ishot" =>1,
        "name" => "埃及女王",
        "service_id" =>2527,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905230659207.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=sdmn&language=zh-cn",
        "gamecode" => "sdmn",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022582040182.png",
        "ishot" =>1,
        "name" => "四大美女",
        "service_id" =>2519,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905224644103.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mpg&language=zh-cn",
        "gamecode" => "mpg",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112703251314415.png",
        "ishot" =>1,
        "name" => "粉红女郎",
        "service_id" =>3304,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905231692960.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ryts&language=zh-cn",
        "gamecode" => "ryts",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018081621344445228.png",
        "ishot" =>1,
        "name" => "人猿泰山",
        "service_id" =>2280,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905223646229.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mczbz&language=zh-cn",
        "gamecode" => "mczbz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018053123073644983.png",
        "ishot" =>1,
        "name" => "船长宝藏",
        "service_id" =>3316,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905245195327.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Fishing&language=zh-cn",
        "gamecode" => "Fishing",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018041001590191972.png",
        "ishot" =>1,
        "name" => "捕鱼达人",
        "service_id" =>2026,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905221382851.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mnys&language=zh-cn",
        "gamecode" => "mnys",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018012705565113933.png",
        "ishot" =>1,
        "name" =>"闹元宵",
        "service_id" =>3308,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091905241711404.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=panpasixiongying&language=zh-cn",
        "gamecode" =>  "panpasixiongying",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018041008340944551.png",
        "ishot" =>0,
        "name" => "潘帕斯雄鹰",
        "service_id" =>2528,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901344287415.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=qunxshanyao&language=zh-cn",
        "gamecode" =>  "qunxshanyao",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018043005042765698.png",
        "ishot" =>0,
        "name" => "群星闪耀",
        "service_id" =>2529,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901345610545.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mjqqm&language=zh-cn",
        "gamecode" => "mjqqm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018041105451873884.png",
        "ishot" =>0,
        "name" => "激情球迷",
        "service_id" =>3311,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901352273262.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mjqsjb&language=zh-cn",
        "gamecode" => "mjqsjb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018040906135491488.png",
        "ishot" =>0,
        "name" => "激情世界杯",
        "service_id" =>3312,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901353782252.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mjxzb&language=zh-cn",
        "gamecode" => "mjxzb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018041105443711702.png",
        "ishot" =>0,
        "name" => "金靴争霸",
        "service_id" =>3310,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901360736234.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hjyj&language=zh-cn",
        "gamecode" => "hjyj",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018050201280681782.png",
        "ishot" =>0,
        "name" => "黄金右脚",
        "service_id" =>2278,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901401682793.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jqzb&language=zh-cn",
        "gamecode" => "jqzb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018041201443580906.png",
        "ishot" =>0,
        "name" => "金球争霸",
        "service_id" =>2277,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901355570575.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=sjbjxw&language=zh-cn",
        "gamecode" => "sjbjxw",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018040906121592261.png",
        "ishot" =>0,
        "name" => "世界杯吉祥物",
        "service_id" =>2279,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901365597228.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Angrybirds&language=zh-cn",
        "gamecode" =>  "Angrybirds",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018030203003154415.png",
        "ishot" =>0,
        "name" => "愤怒的小鸟",
        "service_id" =>2025,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901375710367.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hlm&language=zh-cn",
        "gamecode" => "hlm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022583693360.png",
        "ishot" =>0,
        "name" =>"红楼梦",
        "service_id" =>2521,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901372028103.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Zodiac&language=zh-cn",
        "gamecode" => "Zodiac",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018030202494562851.png",
        "ishot" =>0,
        "name" => "十二生肖",
        "service_id" =>2024,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901374087565.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=PVZ&language=zh-cn",
        "gamecode" => "PVZ",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112101360986521.png",
        "ishot" =>0,
        "name" => "植物大战僵尸",
        "service_id" =>2020,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2020.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zhw&language=zh-cn",
        "gamecode" => "zhw",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916433961360.png",
        "ishot" =>0,
        "name" =>"指环王",
        "service_id" =>2507,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2507.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xj&language=zh-cn",
        "gamecode" => "xj",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091202201783423.png",
        "ishot" =>0,
        "name" =>"仙剑",
        "service_id" =>2501,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901384892661.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wsgyc&language=zh-cn",
        "gamecode" => "wsgyc",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111302473726411.png",
        "ishot" =>0,
        "name" => "武圣关云长",
        "service_id" =>2267,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901381783235.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=rgyc&language=zh-cn",
        "gamecode" => "rgyc",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018020101515635013.png",
        "ishot" =>0,
        "name" => "瑞狗迎春",
        "service_id" =>2273,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2273.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jiaods&language=zh-cn",
        "gamecode" => "jiaods",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018031522401692142.png",
        "ishot" =>0,
        "name" =>"角斗士",
        "service_id" =>2526,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2526.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Panda&language=zh-cn",
        "gamecode" => "Panda",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112022160797598.png",
        "ishot" =>0,
        "name" => "功夫熊猫",
        "service_id" =>2018,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Avatar&language=zh-cn",
        "gamecode" => "Avatar",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017113008412149450.png",
        "ishot" =>0,
        "name" =>"阿凡达",
        "service_id" =>2022,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2022.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Constellation&language=zh-cn",
        "gamecode" =>  "Constellation",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018091901391342980.png",
        "ishot" =>0,
        "name" => "十二星座",
        "service_id" =>2023,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901391514316.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Mowf&language=zh-cn",
        "gamecode" => "Mowf",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022345374235.png",
        "ishot" =>0,
        "name" => "现代战争",
        "service_id" =>2015,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2015.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wsdxl&language=zh-cn",
        "gamecode" => "wsdxl",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018032022162526649.png",
        "ishot" =>0,
        "name" => "神雕侠侣",
        "service_id" =>3204,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018091901393328007.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=nxzqd&language=zh-cn",
        "gamecode" => "nxzqd",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111302454871580.png",
        "ishot" =>0,
        "name" => "女校足球队",
        "service_id" =>2264,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2264.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wxajh&language=zh-cn",
        "gamecode" => "wxajh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110905070660710.png",
        "ishot" =>0,
        "name" => "笑傲江湖",
        "service_id" =>3203,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3203.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Pirates&language=zh-cn",
        "gamecode" => "Pirates",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022354360896.png",
        "ishot" =>0,
        "name" => "加勒比海盗",
        "service_id" =>2017,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2017.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wjs&language=zh-cn",
        "gamecode" => "wjs",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092014054531579.png",
        "ishot" =>0,
        "name" => "拉斯维加斯",
        "service_id" =>2258,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2258.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hdcf&language=zh-cn",
        "gamecode" => "hdcf",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017090410410526545.png",
        "ishot" =>0,
        "name" => "海盗财富",
        "service_id" =>2504,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2504.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gwmy&language=zh-cn",
        "gamecode" => "gwmy",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017090410432342588.png",
        "ishot" =>0,
        "name" => "怪物命运",
        "service_id" =>2510,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2510.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bxjg&language=zh-cn",
        "gamecode" => "bxjg",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017090410452968587.png",
        "ishot" =>0,
        "name" => "变形金刚",
        "service_id" =>2001,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2001.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jg&language=zh-cn",
        "gamecode" => "jg",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017090410460922851.png",
        "ishot" =>0,
        "name" =>"金刚",
        "service_id" =>2003,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2003.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mjxw&language=zh-cn",
        "gamecode" => "mjxw",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017090410470280077.png",
        "ishot" =>0,
        "name" => "摸金校尉",
        "service_id" =>2002,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2002.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=myxj&language=zh-cn",
        "gamecode" => "myxj",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091108553058429.png",
        "ishot" =>0,
        "name" => "梦游仙境",
        "service_id" =>2502,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2502.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=80tlx&language=zh-cn",
        "gamecode" => "80tlx",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091202205542367.png",
        "ishot" =>0,
        "name" => "80天旅行",
        "service_id" =>2503,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2503.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=bsz&language=zh-cn",
        "gamecode" => "bsz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916430593385.png",
        "ishot" =>0,
        "name" =>"白蛇传",
        "service_id" =>2506,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2506.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=fsb&language=zh-cn",
        "gamecode" => "fsb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916442729276.png",
        "ishot" =>0,
        "name" =>"封神榜",
        "service_id" =>2508,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2508.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=tjr&language=zh-cn",
        "gamecode" => "tjr",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916464159630.png",
        "ishot" =>0,
        "name" =>"淘金热",
        "service_id" =>2004,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2004.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Route66&language=zh-cn",
        "gamecode" => "Route66",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916472218429.png",
        "ishot" =>0,
        "name" =>"66路",
        "service_id" =>2005,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2005.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=azteke&language=zh-cn",
        "gamecode" => "azteke",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916481767206.png",
        "ishot" =>0,
        "name" => "阿兹特克",
        "service_id" =>2006,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2006.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Egypt&language=zh-cn",
        "gamecode" => "Egypt",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916490189103.png",
        "ishot" =>0,
        "name" =>"埃及",
        "service_id" =>2007,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2007.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=kh&language=zh-cn",
        "gamecode" => "kh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916493420590.png",
        "ishot" =>0,
        "name" =>"狂欢",
        "service_id" =>2008,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2008.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zsjtq&language=zh-cn",
        "gamecode" => "zsjtq",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916501499313.png",
        "ishot" =>0,
        "name" => "中世纪特权",
        "service_id" =>2009,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2009.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=dqdg&language=zh-cn",
        "gamecode" => "dqdg",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017091916510717964.png",
        "ishot" =>0,
        "name" => "大秦帝国",
        "service_id" =>2010,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2010.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mny&language=zh-cn",
        "gamecode" => "mny",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121205401559170.png",
        "ishot" =>0,
        "name" => "埃及艳后",
        "service_id" =>2260,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2260.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hyrz&language=zh-cn",
        "gamecode" => "hyrz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092014004276926.png",
        "ishot" =>0,
        "name" => "火影忍者",
        "service_id" =>2251,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2251.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=sg&language=zh-cn",
        "gamecode" => "sg",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092014023182530.png",
        "ishot" =>0,
        "name" => "欢乐水果",
        "service_id" =>2252,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2252.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jtbw&language=zh-cn",
        "gamecode" => "jtbw",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092014024852033.png",
        "ishot" =>0,
        "name" => "街头霸王",
        "service_id" =>2253,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2253.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zjsn&language=zh-cn",
        "gamecode" => "zjsn",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018041605194668518.png",
        "ishot" =>0,
        "name" => "战舰少女",
        "service_id" =>2254,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2254.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zgf&language=zh-cn",
        "gamecode" => "zgf",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018020204373487866.png",
        "ishot" =>0,
        "name" => "东方国度",
        "service_id" =>2255,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2255.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=nz&language=zh-cn",
        "gamecode" => "nz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092014043045815.png",
        "ishot" =>0,
        "name" => "西部牛仔",
        "service_id" =>2256,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2256.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hxdl&language=zh-cn",
        "gamecode" => "hxdl",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017092014050553416.png",
        "ishot" =>0,
        "name" => "幻想大陆",
        "service_id" =>2257,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2257.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=nz2&language=zh-cn",
        "gamecode" => "nz2",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121205395730547.png",
        "ishot" =>0,
        "name" => "荒野大镖客",
        "service_id" =>2259,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2259.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xlcs&language=zh-cn",
        "gamecode" => "xlcs",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111302420570735.png",
        "ishot" =>0,
        "name" => "希腊传说",
        "service_id" =>2261,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2261.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=lyxz&language=zh-cn",
        "gamecode" => "lyxz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111302505665478.png",
        "ishot" =>0,
        "name" => "绿野仙踪",
        "service_id" =>2270,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2270.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gdzw&language=zh-cn",
        "gamecode" => "gdzw",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111302515076235.png",
        "ishot" =>0,
        "name" => "格斗之王",
        "service_id" =>2272,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2272.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=hzzh&language=zh-cn",
        "gamecode" => "hzzh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122504355426552.png",
        "ishot" =>0,
        "name" => "黑珍珠号",
        "service_id" =>2511,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2511.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=my&language=zh-cn",
        "gamecode" => "my",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110722352877355.png",
        "ishot" =>0,
        "name" =>"玛雅",
        "service_id" =>2513,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2513.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=smdf&language=zh-cn",
        "gamecode" => "smdf",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111001313610979.png",
        "ishot" =>0,
        "name" => "神秘东方",
        "service_id" =>2515,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2515.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=qxqy&language=zh-cn",
        "gamecode" => "qxqy",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022594348242.png",
        "ishot" =>0,
        "name" => "七夕情缘",
        "service_id" =>2518,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2518.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wtlbb&language=zh-cn",
        "gamecode" => "wtlbb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110801241697526.png",
        "ishot" =>0,
        "name" => "天龙八部",
        "service_id" =>3201,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3201.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wldj&language=zh-cn",
        "gamecode" => "wldj",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110801242710086.png",
        "ishot" =>0,
        "name" =>"鹿鼎记",
        "service_id" =>3202,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3202.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mlfm&language=zh-cn",
        "gamecode" => "mlfm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110823085241994.png",
        "ishot" =>0,
        "name" => "幸运水果机",
        "service_id" =>3301,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3301.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Eiffel&language=zh-cn",
        "gamecode" => "Eiffel",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111422092183323.png",
        "ishot" =>0,
        "name" =>"埃菲尔",
        "service_id" =>2011,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2011.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Nysymbols&language=zh-cn",
        "gamecode" => "Nysymbols",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110803164226259.png",
        "ishot" =>0,
        "name" => "新年符号",
        "service_id" =>2012,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2012.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Pinup&language=zh-cn",
        "gamecode" => "Pinup",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110803225522433.png",
        "ishot" =>0,
        "name" => "性感女神",
        "service_id" =>2013,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071108433983837.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Lushwater&language=zh-cn",
        "gamecode" => "Lushwater",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022360361431.png",
        "ishot" =>0,
        "name" => "甜水绿洲",
        "service_id" =>2016,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2016.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=frnc&language=zh-cn",
        "gamecode" => "frnc",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017110801592798105.png",
        "ishot" =>0,
        "name" => "富饶农场",
        "service_id" =>2512,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2512.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=zz&language=zh-cn",
        "gamecode" => "zz",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112101320467803.png",
        "ishot" =>0,
        "name" =>"战争",
        "service_id" =>2516,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2516.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=nznh&language=zh-cn",
        "gamecode" => "nznh",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022590756819.png",
        "ishot" =>0,
        "name" => "哪吒闹海",
        "service_id" =>2517,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2517.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=wsdf&language=zh-cn",
        "gamecode" => "wsdf",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022585497551.png",
        "ishot" =>0,
        "name" => "武松打虎",
        "service_id" =>2522,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2522.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=xxgpklr&language=zh-cn",
        "gamecode" => "xxgpklr",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017111302433857303.png",
        "ishot" =>0,
        "name" => "吸血鬼PK狼人",
        "service_id" =>2262,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2262.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Doomsday&language=zh-cn",
        "gamecode" => "Doomsday",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122022362748201.png",
        "ishot" =>0,
        "name" => "世界末日",
        "service_id" =>2014,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2014.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Jurassic&language=zh-cn",
        "gamecode" => "Jurassic",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112021463581627.png",
        "ishot" =>0,
        "name" =>"侏罗纪",
        "service_id" =>2019,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018080803163756345.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mmm&language=zh-cn",
        "gamecode" => "mmm",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112703233619685.png",
        "ishot" =>0,
        "name" => "众神之王",
        "service_id" =>3303,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3303.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=scs&language=zh-cn",
        "gamecode" => "scs",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121100104035698.png",
        "ishot" =>0,
        "name" => "女校啦啦队",
        "service_id" =>3102,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071109562485901.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=ckxt&language=zh-cn",
        "gamecode" => "ckxt",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121421333812694.png",
        "ishot" =>0,
        "name" => "刺客信条",
        "service_id" =>2268,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2268.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=yda&language=zh-cn",
        "gamecode" => "yda",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122504361133857.png",
        "ishot" =>0,
        "name" =>"印第安",
        "service_id" =>2514,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2514.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=gmly&language=zh-cn",
        "gamecode" => "gmly",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121205412725773.png",
        "ishot" =>0,
        "name" => "古墓丽影",
        "service_id" =>2269,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2269.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=nxglq&language=zh-cn",
        "gamecode" => "nxglq",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122005194953829.png",
        "ishot" =>0,
        "name" => "女校橄榄球",
        "service_id" =>2265,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2265.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=sst&language=zh-cn",
        "gamecode" => "sst",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122000084658191.png",
        "ishot" =>0,
        "name" => "女校游泳队",
        "service_id" =>3101,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3101.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mpjs&language=zh-cn",
        "gamecode" => "mpjs",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122001064624993.png",
        "ishot" =>0,
        "name" =>"鸟叔",
        "service_id" =>3305,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3305.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=msd&language=zh-cn",
        "gamecode" => "msd",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017122005094328154.png",
        "ishot" =>0,
        "name" => "灌篮高手",
        "service_id" =>3306,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3306.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=mhxy&language=zh-cn",
        "gamecode" => "mhxy",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121421330525930.png",
        "ishot" =>0,
        "name" => "梦幻西游",
        "service_id" =>2263,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2263.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=sgt&language=zh-cn",
        "gamecode" => "sgt",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121806032580303.png",
        "ishot" =>0,
        "name" => "女校体操队",
        "service_id" =>3103,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/3103.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=nxjdb&language=zh-cn",
        "gamecode" => "nxjdb",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121421332374677.png",
        "ishot" =>0,
        "name" => "女校剑道部",
        "service_id" =>2266,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2018071108420916259.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jxqy&language=zh-cn",
        "gamecode" => "jxqy",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017121205414022654.png",
        "ishot" =>0,
        "name" => "剑侠情缘",
        "service_id" =>2271,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2271.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=Watch&language=zh-cn",
        "gamecode" => "Watch",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2017112101343317808.png",
        "ishot" =>0,
        "name" => "守望英雄",
        "service_id" =>2021,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2021.png",
    ),
    array(
        "categoryid" =>9,
        "game_url" => "https://h5.chichengwl.com/game?type=h5&gamecode=jgwc&language=zh-cn",
        "gamecode" => "jgwc",
        "gt" => "slot",
        "img" => "https://h5.chichengwl.com/global/files/images/2018012907503299567.png",
        "ishot" =>0,
        "name" => "金狗旺财",
        "service_id" =>2523,
        "small_img" =>"https://h5.chichengwl.com/global/files/images/2523.png",
    ),
);

// 后台游戏名称列表
foreach ($aFgGames as $k => $v){
    $afgGameList[$v['service_id']] = $v['name'];
}

//新版手机版游戏名称列表数据格式
foreach ($aFgGames as $k => $v){
    $fgGameList[$k]['gameId'] = $v['service_id'];
    $fgGameList[$k]['gameName'] = $v['name'];
    $fgGameList[$k]['gameIcon'] = $v['service_id'] . '.png';
    //$fgGameList[$k]['gameIcon'] = $v['small_img'];
    $fgGameList[$k]['gameRuleUrl'] = $v['game_url'];
}

//体育旧版游戏名称列表数据格式
foreach ($aFgGames as $k => $v){
    $ofgGameList[$k]['gameid'] = $v['service_id'];
    $ofgGameList[$k]['name'] = $v['name'];
    $ofgGameList[$k]['type'] = $v['gt'];
    $ofgGameList[$k]['gameurl'] = $v['small_img'];
    //$ofgGameList[$k]['gameRuleUrl'] = $v['game_url'];
}

// 游戏类型
$fgGameGts = array(
    'arcade'=>'街机',
    'chess'=>'棋牌',
    'slot'=>'老虎机',
    'hunter'=>'捕猎',
);

// 设备类型
$fgDevices = array(
    '1'=>'PC端',
    '2'=>'IOS横',
    '3'=>'IOS竖',
    '4'=>'安卓横',
    '5'=>'安卓竖',
    '6'=>'其他横',
    '7'=>'其他竖',
);


// 捕鱼类型
$hfgTypes = array(
    '1'=>'普通场景',
    '2'=>'jp奖账单',
    '6'=>'买鱼注单',
    '14'=>'激光炮',
    '15'=>'boss赛功能',
    '16'=>'基金购买',
    '17'=>'领取奖金',
    '18'=>'幸运宝箱',
    '19'=>'电磁炮',
    '20'=>'连环炸弹',
    '21'=>'闪电',
    '22'=>'世界boss场景',
    '23'=>'世界boss排行榜奖励',
    '24'=>'世界最后一击奖励',
    '25'=>'黑洞鱼',
);

